version: "3"

services:
  csv_update:
    container_name: csv_update
    depends_on: 
      - rabbitmq
    build:
      context: ./csv_update
      dockerfile: Dockerfile  
    ports:
      - "8080:5000"

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"